name: automationscript
on:
 push:
  branches:
  - main
jobs:
 job_one:
   name: Build job
   runs-on: ubuntu-latest
   steps:
    - name: cloning
      uses: actions/checkout@v4
    - name: generating image from dockerfile
      run: docker build -t img .
    - name: running container
      run: docker run --name cont img:latest   
 job_two:
   name: pushing_image
   runs-on: ubuntu-latest 
   permissions:
    content: read
    packages: write
   steps: 
    - name: cloning repo
      uses: actions/checkout@v4
    - name: logging in to registry
      uses: docker/login-action@v3
      with: 
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}
    - name: building and pushing image 
      run: | 
           IMAGE_ID=ghcr.io/rupalirai786/img:latest
           IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')             
           docker build -t $IMAGE_ID .
           docker push $IMAGE_ID
