name: automationscript
on:
 push:
  branches:
  - main
jobs:
   job_one:
   name: trivy scanner plus image pushing plus running container
   runs-on: ubuntu-latest
   permissions:
      contents: read
      packages: write
   steps:
    - name: installing trivy
      run: |
            sudo apt-get install wget gnupg
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
            echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update
            sudo apt-get install trivy 
            
    - name: cloning repo
      uses: actions/checkout@v4
    - name: logging in to registry
      uses: docker/login-action@v3
      with: 
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}
            
    - name: scanning image and running container
      run: |  
            IMAGE_ID=ghcr.io/rupalirai786/img:latest
            IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]') 
            docker build -t $IMAGE_ID .
            trivy image --exit-code 1 $IMAGE_ID
            if [$? -eq 0]; then
             docker push $IMAGE_ID
             docker run --name cont $IMAGE_ID
            fi 
    